---
title: "Syria Night Lights"
author: "Daniel K Baissa"
date: "2022-11-01"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(raster)
library(tidyverse)
library(sf)
```

```{r}
Syria <- st_read("Shapefiles/syr_admbnda_adm0_uncs_unocha_20201217.shp")
```

```{r}
F2006 <-
  raster("Syria_Albedo_Nightlights/Syria_Data/F15_20060101_20060131.cloud2.light1.marginal0.line_screened.avg_vis.tif")
F2011 <- raster("Syria_Albedo_Nightlights/Syria_Data/F18_20110101_20110131.cloud2.light1.marginal0.glare2.line_screened.avg_vis.tif")
```

```{r}
e <- as(extent(Syria), 'SpatialPolygons')
crs(e) <- "+proj=longlat +datum=WGS84 +no_defs"
F2006 <- crop(F2006, e)
# F2006 <- mask(F2006, Syria)
F2011 <- crop(F2011, e)
# F2011 <- mask(F2011, Syria)
plot(F2011)
```

```{r}
ppside <- 2
h <- ceiling(ncol(F2011)/ppside)
v <- ceiling(nrow(F2011)/ppside)
agg <- aggregate(F2011,fact=c(h,v))
agg[]    <- 1:ncell(agg)
agg_poly <- rasterToPolygons(agg)
plot(agg_poly)
```


cropping the shape



```{r}
 # Extract raster values to list object
    r.vals <- raster::extract(F2011, agg_poly)
    # Use list apply to calculate mean for each polygon
    r.mean <- lapply(r.vals, FUN=mean, na.rm = T)
    

    # Join mean values to polygon data
    agg_poly@data <- data.frame(agg_poly@data, NL=unlist(r.mean))
    
    
agg_poly = st_as_sf(agg_poly)     
```


```{r}
ggplot()+
  geom_sf(data = agg_poly, mapping =  aes(fill = NL))
df <- st_intersection(agg_poly, Syria)

```

```{r}
ggplot()+
  geom_sf(data = df, mapping =  aes(color = NULL, fill = log(NL)))+
  scale_fill_viridis_c(option = "H") +
  theme_classic()
```

```{r}
try(st_delete("syria.shp"))
st_write(df, "syria.shp", dataset_options = "OVERWRITE=T")
```


```{r}
min(log(df$NL))
```

# Now let's automate this

First I need to get R to read all of the rasters and then I will loop the above raster means thing.

```{r}
filenames <- list.files("Monthly_DMSP-OLS", pattern=".avg_vis.tif", full.names=TRUE)
```
```{r}
r <- raster(filenames[1])
```

```{r}
ppside <- 4
h <- ceiling(ncol(r)/ppside)
v <- ceiling(nrow(r)/ppside)
agg <- aggregate(r,fact=c(h,v))
agg[]    <- 1:ncell(agg)
agg_poly <- rasterToPolygons(agg)
plot(agg_poly)
```

```{r}
    r.vals <- raster::extract(r, agg_poly)
    # Use list apply to calculate mean for each polygon
    r.mean <- lapply(r.vals, FUN=mean, na.rm = T)
    # Join mean values to polygon data
    agg_poly@data <- data.frame(agg_poly@data, NL_month_1=unlist(r.mean))
    
```

```{r}
# for (i in 2:length(filenames)) {
  for (i in 2:3) {

  r <- raster(filenames[i])
      r.vals <- raster::extract(r, agg_poly)
    # Use list apply to calculate mean for each polygon
    r.mean <- lapply(r.vals, FUN=mean, na.rm = T)
    # Join mean values to polygon data
    agg_poly@data <- data.frame(agg_poly@data, paste0("NL_month_", i)=unlist(r.mean))
    print(paste(i, "of", length(filenames)))
}
```

